version: 2.1


    
workflows:
  test_build_deploy:
   jobs: 
    - build
    
  jobs:
   build:
    docker:
     - image: alpine:latest
    steps:
    - checkout
    - run:
      name: "Install linting tool"
      command: echo "Installation successfull"
    - run: 
      name: "Run linting on the root directory"
      command: echo "linting successfull"
      working_directory: "./"
 
